# create a dev conda environment with: `make create_env` or `conda env create -f environment.yml`
name: pianoptim
channels:
- conda-forge
dependencies:
- biorbd >=1.11.1
- matplotlib
- pyqt
- pyqtgraph
- python-graphviz
- pandas